### ISSUE TITLE
Plugin Roadmap

### ISSUE THREAD

**Issue by toddmilliken** [bu-ist/bu-blocks#2]
### Build plugin structure
- [x] [wp scaffold plugin](https://developer.wordpress.org/cli/commands/scaffold/plugin/): Adds the base functionality for grunt tasks, PHPUnit tests
- [x] [BU's sample plugin/feature/use_docker branch](https://github.com/bu-ist/sample-plugin/tree/feature/use_docker): Adds the docker-compose and bin scripts for setting up tests locally with docker
- [x] [WordPress Plugin Boilerplate](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate): Adds base plugin structure using a class-based approach and separation of admin-facing hooks from public-facing hooks. Note: It may be a good idea to also add in namespaces, and maybe an autoloader for all classes. Will revisit
- [ ] [create-guten-block](https://github.com/ahmadawais/create-guten-block): Provides a zero-configuration boilerplate for creating blocks for the new editor. This seems to be the standard by which most plugin authors prefer to create blocks, as it takes care of es6/7/8/Next, babel, webpack configurations and has one `cgb-scripts` dependency.
- [ ] [wp scaffold block](https://developer.wordpress.org/cli/commands/scaffold/block/): Provides boilerplate, mainly used for creating blocks using standard ECMAScript 5 JS approaches that don't need babel to transpile it to JS browsers can understand.

### Research and identify approach for managing blocks
- [x] Identify best way to retrieve all blocks.  
(JS was chosen due to lack of PHP API support. See https://github.com/WordPress/gutenberg/issues/8352 and https://github.com/WordPress/gutenberg/projects/18 for status on server-side availability of blocks.
- [x] Enqueue necessary gutenberg assets so information about registered gutenberg blocks can be retrieved.
- [x] Limit the scope of how the plugin enqueues admin JS code (only on posts with gutenberg + the plugin settings page should have the plugin scripts enqueued; everywhere else in the admin should be left alone)
- [x] Test unregistering a block via JS using  'wp.blocks.unregisterBlockType()'.
- [x] Test retrieval of all available blocks and all their meta (title, desc, icon, category, [extra BU meta?])
- [x] Test looping through blocks and unregistering some from an array of undesirable blocks.
    - [x] First, test a static array of blocks to unregister purely in JavaScript
    - [x] Second, test a localized "disabled" blocks array that depends on our plugin's scripts, so plugin js has access to values from PHP code.
    - [x] Third, test looping through values and calling 'wp.blocks.unregisterBlockType()' for each iteration.
    - [x] Fourth, test to see if 3rd party plugins' blocks can be retrieved and unregistered following these methods.

### Add a developer API
- [x] Add PHP server-side hook for developers to use to define blocks to unregister. Pass this value to `wp_localize_script`
- [ ] Add PHPUnit tests for all hooks.

### Add an admin settings page
- [x] Add plugin settings page so users can disable blocks without the need to interact with the developer API.
- [ ] Define how the UI will look/feel and work. Since blocks can only be reliably be retrieved in JavaScript, it may make sense to create the bulk of the interface in JS (perhaps using React) and interact with either `admin-ajax.php` or the REST API. 
- [ ] Scaffold the structure of the settings page
- [ ] Complete the build of the settings components
- [ ] Ensure data is saved to database, and sanitized properly
- [ ] Consider writing PHPUnit tests for any server-side execution here...

### Identify best way for BU Blocks to include its own blocks
- [ ] Come up with implementation style (none, just a folder of blocks, `create-guten-block` style, PHP class-based approach for each block, etc)
- [ ] Build a couple sample blocks for demonstration purposes, or real-life ones we might actually use.
